tap "manaflow-ai/cmux"

# ─── Formulae ───────────────────────────────────────────────────────────────
brew "atuin"
brew "bat"
brew "cloudflared"
brew "curlie"
brew "fd"
brew "git-delta"
brew "deno"
brew "ffmpeg"
brew "flyctl"
brew "fzf"
brew "gh"
brew "imagemagick"
brew "jq"
brew "just"
brew "mise"
brew "mkcert"

brew "mole"
brew "mprocs"
brew "ripgrep"
brew "rtk"
brew "starship"
brew "helix"
brew "tlrc"
brew "tree"
brew "wget"
brew "yazi"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

# ─── Casks ──────────────────────────────────────────────────────────────────
cask "1password-cli"
cask "chromedriver"
cask "chromium"
cask "cmux"
cask "codex"
cask "cursor"
cask "ghostty"
cask "ollama-app"
cask "orbstack"
cask "raycast"
cask "warp"
