tap "charliesbot/tap"
tap "tobi/try", "https://github.com/tobi/try"

# ─── Formulae ───────────────────────────────────────────────────────────────
brew "atuin"
brew "bat"
brew "btop"
brew "cloudflared"
brew "fd"
brew "git-delta"
brew "deno"
brew "direnv"
brew "dust"
brew "eza"
brew "ffmpeg"
brew "flyctl"
brew "fzf"
brew "gh"
brew "imagemagick"
brew "jq"
brew "just"
brew "lazydocker"
brew "mise"
brew "mkcert"

brew "mole"
brew "mprocs"
brew "ripgrep"
brew "rtk"
brew "starship"
brew "fresh-editor"
brew "tlrc"
brew "tree"
brew "try"
brew "wget"
brew "yazi"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

# ─── Casks ──────────────────────────────────────────────────────────────────
cask "1password-cli"
cask "chai"
cask "chromedriver"
cask "chromium"
cask "codex"
cask "orbstack"
cask "raycast"
cask "visual-studio-code"
cask "warp"
